/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "i2c.h"
#include "timer.h"
#include "i2c_lcd.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	char str[20];
	int count=0;
	//int exit0_flag=0;
	LcdInit();
	TimerInit(1000);
	LcdPuts(LCD_LINE1,"interupt count");
	while(1)
	{
		while(exti0_flag==0)
			;
		count++;
		sprintf(str,"%d",count);
		LcdPuts(LCD_LINE2,str);
		exti0_flag=0;

	}
	return 0;

}


